
{{- $host := dict "name" "DBHOST" "value" "mariadb-server"}}
{{- $user := dict "name" "DBUSER" "value" "root" }}

{{- $secretKeyRef := dict "name" "mariadb-server" "key" "mariadb-root-password" }}
{{- $valueFrom := dict "secretKeyRef" $secretKeyRef }}
{{- $password := dict "name" "DBPASSWORD" "valueFrom" $valueFrom  }}

{{- $db := dict "name" "DBDATABASE" "value" "events_db" }}
{{- $env := list $host $user $password $db }}
{{- $data := dict "Globals" . "name" "api" "image" .Values.api.image "env" $env "replicaCount" .Values.api.replicaCount "port" 8082}}
{{- include "events-app.deployment" $data }}