# Default values for events-app.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# Configuration options for events-website
website:
  # This controls how many events-website pods to deploy
  replicaCount: 3
  image: 
    repository: 360871920119.dkr.ecr.us-east-1.amazonaws.com/events-website
    tag: ""

  # The public port to host on
  port: 80

  # If provided, will deploy a duplicate deployment
  # pointed at a different version
  blueGreenTag: ""

# Configuration options for events-api
api:
  # This controls how many events-website pods to deploy
  replicaCount: 3
  image: 
    repository: 360871920119.dkr.ecr.us-east-1.amazonaws.com/events-api
    tag: ""
  
# Configuration options for events-job
eventsJob: 
  image: 
    repository: 360871920119.dkr.ecr.us-east-1.amazonaws.com/events-job
    tag: ""

# This is to override the chart name.
nameOverride: ""
fullnameOverride: ""