# Default values for events-app.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# Configuration options for events-website
website:
  # This controls how many events-website pods to deploy
  replicaCount: 3
  image: 
    repository: <website-repo-here>
    tag: ""

  # The public port to host on
  port: 80
  containerPort: 8080

  # If provided, will deploy a duplicate deployment
  # pointed at a different version
  blueGreenTag: ""

# Configuration options for events-api
api:
  # This controls how many events-website pods to deploy
  replicaCount: 3
  image: 
    repository: <api-repo-here>
    tag: ""

  containerPort: 8082
  
# Configuration options for events-job
eventsJob: 
  image: 
    repository: <job-repo-here>
    tag: ""

# This is to override the chart name.
nameOverride: ""
fullnameOverride: ""